/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiFlightGet } from '../fn/flight/api-flight-get';
import { ApiFlightGet$Params } from '../fn/flight/api-flight-get';
import { apiFlightGet$Plain } from '../fn/flight/api-flight-get-plain';
import { ApiFlightGet$Plain$Params } from '../fn/flight/api-flight-get-plain';
import { FlightRm } from '../models/flight-rm';

@Injectable({ providedIn: 'root' })
export class FlightService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiFlightGet()` */
  static readonly ApiFlightGetPath = '/api/Flight';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiFlightGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiFlightGet$Plain$Response(params?: ApiFlightGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FlightRm>>> {
    return apiFlightGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiFlightGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiFlightGet$Plain(params?: ApiFlightGet$Plain$Params, context?: HttpContext): Observable<Array<FlightRm>> {
    return this.apiFlightGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FlightRm>>): Array<FlightRm> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiFlightGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiFlightGet$Response(params?: ApiFlightGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FlightRm>>> {
    return apiFlightGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiFlightGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiFlightGet(params?: ApiFlightGet$Params, context?: HttpContext): Observable<Array<FlightRm>> {
    return this.apiFlightGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FlightRm>>): Array<FlightRm> => r.body)
    );
  }

}
