/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookDto {
  flightId?: string;
  numberOfSeats?: number;
  passengerEmail?: string | null;
}
