/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TimePlaceRm } from '../models/time-place-rm';
export interface FlightRm {
  airline?: string | null;
  arrival?: TimePlaceRm;
  departure?: TimePlaceRm;
  id?: string;
  price?: string | null;
  remainingNumberOfSeats?: number;
}
