/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NewPassengerDto {
  email?: string | null;
  firstName?: string | null;
  gender?: boolean;
  lastName?: string | null;
}
